name: Daily Dev Actions
on: [push]
jobs:
  devcard:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.6
        with:
          devcard_id: ${{ ed665ba53c574210bfd677924a99a2c5 }}
